server:
  port: 8080

spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: kuaile+2552
          url: jdbc:mysql://121.196.25.37:3306/db1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          username: root
          password: kuaile+2552
          url: jdbc:mysql://121.196.25.37:3306/db2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
      mp-enabled: true
